on:
  workflow_call:
    secrets:
      GITHUB_TOKEN:
        required: true
      JWTSECRET:
        required: true
      HOST:
        required: true
      USER:
        required: true
      PASSWORD:
        required: true

name: Release

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: restore-build
        with:
          path: |
            ./*
            !node_modules/*
          key: ${{ github.sha }}

      - uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Zip Assets
        run: |
          git clone https://github.com/mx-space/assets.git --depth=1
          rm -rf assets/.git
          cp -R assets out
          cp ecosystem.config.js out
          cd out
          zip -r ../release.zip ./*
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release.zip
          asset_name: release-ubuntu.zip
          asset_content_type: application/zip
  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Exec deploy script with SSH
        uses: appleboy/ssh-action@master
        env:
          JWTSECRET: ${{ secrets.JWTSECRET }}
        with:
          command_timeout: 10m
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          envs: JWTSECRET
          script_stop: true
          script: |
            whoami
            cd
            source ~/.zshrc
            cd mx
            ls -a
            node server-deploy.js --jwtSecret=$JWTSECRET
